# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:55
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
