# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 12:13
from __future__ import unicode_literals

import bookstore.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20171022_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=bookstore.models.Book.get_image_path),
        ),
    ]
