# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:42
from __future__ import unicode_literals

import bookstore.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20171022_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='/media/None/none.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/media/None/none.jpg', upload_to=bookstore.models.Book.get_image_path),
        ),
    ]
