# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:02
from __future__ import unicode_literals

import bookstore.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20171022_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/None/none.jpg', upload_to=bookstore.models.Book.get_image_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='/None/none.jpg', upload_to=bookstore.models.Book.get_thumb_path),
        ),
    ]
